# Generated by Django 3.1.2 on 2020-10-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
                ('other_category', models.ManyToManyField(blank=True, related_name='other_category', to='main.Categories')),
            ],
        ),
    ]
